app/routes.php
<?php
use Faker\Factory as Faker;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Online::updateCurrent();

Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Admin Routes
Route::group(['before' => 'auth|admin'], function()
{
        Route::group(array('prefix' => 'admin'), function()
        {
            //Route::get('users', array('as' => 'admin.users', 'uses' => 'UsersController@users'));
	    //Route::get('roles', array('as' => 'admin.roles', 'uses' => 'UsersController@roles'));
	    Route::resource('pages', 'PagesController');
	    Route::resource('uslugis', 'UslugisController');
	    Route::resource('articles', 'ArticlesController');
	    Route::resource('histories', 'HistoriesController');
	    Route::resource('albums', 'AlbumsController');
	    Route::resource('photos', 'PhotosController');
	    Route::resource('comments', 'CommentsController');
	    Route::resource('users', 'UsersController');
	    Route::resource('menu', 'MenunamesController');
	    Route::post('/set/admin', array('as' => 'admin.set.admin', 'uses' => 'UsersController@set_admin'));
        });
});

# Registration
Route::group(['before' => 'guest'], function()
{
     Route::post('/user/login', array('as' => 'user.login', 'uses' => 'UsersController@login'));
     Route::get('/user/register', array('as' => 'user.register', 'uses' => 'UsersController@register'));
     Route::post('/user/register', array('as' => 'user.register.post', 'uses' => 'UsersController@register_post'));
     Route::get('/user/activate/{activationCode}', array('as' => 'user.activate', 'uses' => 'UsersController@activate'));
     
	
});

# Авторизованый
Route::group(['before' => 'auth'], function()
{
	Route::get('/user/logout', array('as' => 'user.logout', 'uses' => 'UsersController@user_logout'));
	
	Route::get('/user/id-{id}', array('as' => 'user.id', 'uses' => 'UsersController@information'));
	Route::get('/user/id-{id}/settings', array('as' => 'user.settings', 'uses' => 'UsersController@settings'));
	Route::post('/user/id-{id}/settings', array('as' => 'user.settings.save', 'uses' => 'UsersController@settings_save'));
	Route::get('/user/id-{id}/information', array('as' => 'user.information', 'uses' => 'UsersController@information'));
	Route::post('/user/id-{id}/information/about/save', array('as' => 'user.information.about.save', 'uses' => 'UsersController@information_about_save'));
	Route::post('/user/id-{id}/information/thinking/save', array('as' => 'user.information.thinking.save', 'uses' => 'UsersController@information_thinking_save'));
	Route::post('/user/profile/save/name', array('as' => 'user.profile.save.name', 'uses' => 'UsersController@user_profile_save_name'));
	Route::post('/user/profile/save/telephone', array('as' => 'user.profile.save.telephone', 'uses' => 'UsersController@user_profile_save_telephone'));
	Route::post('/user/profile/save/city', array('as' => 'user.profile.save.city', 'uses' => 'UsersController@user_profile_save_city'));
	Route::post('/user/profile/save/bithday', array('as' => 'user.profile.save.bithday', 'uses' => 'UsersController@user_profile_save_bithday'));
	Route::post('/user/profile/save/gender', array('as' => 'user.profile.save.gender', 'uses' => 'UsersController@user_profile_save_gender'));
	Route::post('/user/profile/save/gender-search', array('as' => 'user.profile.save.gender.search', 'uses' => 'UsersController@user_profile_save_gender_search'));
	Route::post('/user/profile/save/point', array('as' => 'user.profile.save.point', 'uses' => 'UsersController@user_profile_save_point'));
	Route::post('/user/profile/save/work', array('as' => 'user.profile.save.work', 'uses' => 'UsersController@user_profile_save_work'));
	Route::post('/user/profile/save/vuz', array('as' => 'user.profile.save.vuz', 'uses' => 'UsersController@user_profile_save_vuz'));
	Route::post('/user/profile/save/school', array('as' => 'user.profile.save.school', 'uses' => 'UsersController@user_profile_save_school'));
	
	Route::get('/user/id-{id}/friends', array('as' => 'user.friends', 'uses' => 'UsersController@friends'));
	Route::get('/friends/add/{id}', array('as' => 'friends.add', 'uses' => 'UsersController@friendsAdd'));
	Route::get('/friends/apply/{id}', array('as' => 'friends.apply', 'uses' => 'UsersController@applyFriend'));
	Route::get('/friends/cencel/{id}', array('as' => 'friends.cencel', 'uses' => 'UsersController@cencelFriend'));
	Route::get('/friends/del/{id}', array('as' => 'friends.del', 'uses' => 'UsersController@delFriend'));
	
	Route::post('/upload/avatar/{id}', array('as' => 'upload.avatar', 'uses' => 'FileController@uploadAvatar'));
	Route::post('/upload/fon/{id}', array('as' => 'upload.fon', 'uses' => 'FileController@uploadFon'));
	Route::controller('filemanager', 'FilemanagerLaravelController');
	Route::post('/upload/{folder}', array('as' => 'upload.image', 'uses' => 'FileController@uploadImage'));
	Route::post('/upl/photos', array('as' => 'upload.photos', 'uses' => 'FileController@uploadPhotos'));
	
	Route::get('/profiles/all', array('as' => 'profiles', 'uses' => 'UsersController@profiles'));
	
	Route::get('/user/id-{id}/photos', array('as' => 'user.photos', 'uses' => 'AlbumsController@photos'));
	Route::get('/user/id-{id}/photos/album/{slug}', array('as' => 'user.album', 'uses' => 'PhotosController@album'));
	Route::resource('albums', 'AlbumsController');
	Route::resource('photos', 'PhotosController');
	Route::get('photos/{id}/nextprev', array('as' => 'photos.nextprev', 'uses' => 'PhotosController@nextprev'));
        
	Route::resource('comments', 'CommentsController');
	
	Route::get('/user/id-{id}/messages', array('as' => 'user.messages', 'uses' => 'ChatsController@messages'));
	Route::resource('histories', 'HistoriesController', array('only' => array('create', 'store')));
	Route::post('/chats/sendme/ajax', array('as' => 'chats.sendme.ajax', 'uses' => 'ChatsController@sendME'));
	
	Route::post('/pay/success', array('as' => 'pay.success', 'uses' => 'HomeController@success'));
	Route::post('/pay/fail', array('as' => 'pay.fail', 'uses' => 'HomeController@fail'));
	Route::post('/pay/pending', array('as' => 'pay.pending', 'uses' => 'HomeController@pending'));
	
	Route::post('/star/add', array('as' => 'star.add', 'uses' => 'StarsController@store'));
	
});

Route::get('/', array('as' => 'front', 'uses' => 'HomeController@showWelcome'));
Route::get('/image/users/{id}/{w}/{h}', array('as' => 'user.avatar', 'uses' => 'FileController@avatar'));
Route::get('/image/users/load/{name}/{w}/{h}', array('as' => 'user.avatar.load', 'uses' => 'FileController@avatar_load'));
Route::any('/{slug}', array('as' => 'pages.view', 'uses' => 'PagesController@view'));
Route::get('/image/filemanager/{name}/{w}/{h}/{position}', array('as' => 'image.filemanager', 'uses' => 'FileController@filemanager'));
Route::get('/image/{folder}/{name}/{w}/{h}/{position}', array('as' => 'image.folder', 'uses' => 'FileController@imageFolder'));

Route::get('/uslugi/{slug}', array('as' => 'uslugis.view', 'uses' => 'UslugisController@view'));
Route::get('/article/{slug}', array('as' => 'articles.show', 'uses' => 'ArticlesController@show'));
Route::get('/articles/all', array('as' => 'articles', 'uses' => 'ArticlesController@articles'));
Route::get('/history/{slug}', array('as' => 'histories.show', 'uses' => 'HistoriesController@show'));
Route::get('/histories/all', array('as' => 'histories', 'uses' => 'HistoriesController@histories'));

Route::get('/profiles/json', array('as' => 'profiles.json', 'uses' => 'UsersController@profilesJson'));

Route::get('/profiles/load/chat', array('as' => 'profiles.load.chat', 'uses' => 'ChatsController@loadChat'));
Route::post('/chats/send/message/ajax', array('as' => 'chats.send.message.ajax', 'uses' => 'ChatsController@sendMessageAjax'));
Route::post('/chats/load/{id}/ajax', array('as' => 'chats.load.message.ajax', 'uses' => 'ChatsController@loadMessageAjax'));
Route::post('/set/like', array('as' => 'set.like', 'uses' => 'StatisticsController@setLike'));

require app_path().'/menu.php';

app/models/Article.php
<?php

class Article extends \Eloquent {

	 // Don't forget to fill this array
	protected $fillable = [];
        
        protected $guarded = ['_token', 'image_ajax'];
        
        public static $sluggable = array(
		'build_from' => 'name',
		'save_to'    => 'slug',
	);
        
        public static $rules = array(
		'name'     => 'required|min:2',
		'body'      => 'required|min:10',
	);
	
	public static $messages = array(
               
	       'name.required'        => 'Поле "Заголовок" обязательно для заполнения',
	       'name.min'             => 'Количество символов в поле "Заголовок" должно быть не менее 2.',
	       'body.required'         => 'Поле "Содержание" обязательно для заполнения',
	       'body.min'              => 'Количество символов в поле "Содержание" должно быть не менее 10',
        );
        
        public function scopeSlug($query, $slug)
	{
	  return $query->whereSlug($slug)->first();
	}
        
        public function profile()
	{
	    return $this->hasOne('Profile','user_id', 'user_id');
	}
	
	public function likes()
	{
	    return $this->hasMany('Like', 'type_id', 'id')->where('type', 'article');
	}
	
	public function looks()
	{
	    return $this->hasMany('Look', 'type_id', 'id')->where('type', 'article');
	}

}

app/controllers/ArticlesController.php
<?php

class ArticlesController extends \BaseController {

	/**
	 * Display a listing of articles
	 *
	 * @return Response
	 */
	public function index()
	{
		$articles = Article::orderBy('updated_at', 'desc')->paginate(10);

		return View::make('articles.index', compact('articles'));
	}
	
	/*
	 * function articles
	 * @param 
	 * ---------------------------------------
	 * | 
	 * ---------------------------------------
	 */
	
	public function articles() {
		
		$articles = Article::orderBy('updated_at', 'desc')->paginate(10);

		return View::make('articles.articles', compact('articles'));
	}

	/**
	 * Show the form for creating a new article
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('articles.create');
	}

	/**
	 * Store a newly created article in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Article::$rules, Article::$messages);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		Article::create($data);

	        return Redirect::route('admin.articles.index')->with('success', 'Статья создана.');
	}

	/**
	 * Display the specified article.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($slug)
	{
		$article = Article::slug($slug);
		
		if (empty($article->id))
		{
			App::abort(404);
		}
		
		Event::fire('show.article', array($article));

		return View::make('articles.show', compact('article'));
	}

	/**
	 * Show the form for editing the specified article.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$article = Article::find($id);

		return View::make('articles.edit', compact('article'));
	}

	/**
	 * Update the specified article in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$article = Article::findOrFail($id);

		$validator = Validator::make($data = Input::all(), Article::$rules, Article::$messages);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$article->update($data);

		return Redirect::route('admin.articles.index')->with('success', 'Статья обновлена.');
	}

	/**
	 * Remove the specified article from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Article::destroy($id);

		return Redirect::route('admin.articles.index')->with('success', 'Статья удалена.');
	}

}

app/views/articles/articles.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Статьи | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')

@stop

@section('content')
                
<div id="page">
    <div class="panel-body">
        <div class="bg-light lter b-b wrapper-md ng-scope">
            <h1 class="m-n font-thin h3">Статьи</h1>
        </div>
        <div class="blog-post">
            <div class="panel">
                <div id="articlesAll" class="wrapper-lg">
                    @if($articles->count())
                        @foreach($articles as $article)
                            <div class="rows">
                                @if($article->image)
                                <div class="col-1">
                                    <a href="{{ route('articles.show', $article->slug) }}"><img src="{{ route('image.folder', array('articles', $article->image, 100, 100, 'center')) }}" class="img-thumbnail m-r-md pull-left"></a>
                                </div>
                                @endif
                                <div class="col-2">
                                    <h3 class="m-t-none"><a href="{{ route('articles.show', $article->slug) }}">{{ $article->name }}</a></h3>
                                    <div class="body">{{ str_limit($article->body, $limit = 500, $end = '...') }}</div>
                                </div>
                                <div class="col-3">
                                    <ul class="stats list-inline text-muted">
                                        <li><i class="icon-calendar"></i> {{ date('d.m.Y', strtotime($article->created_at)) }}</li>
                                        <li><i class="icon-user"></i> <a class="text-muted" href="{{ route('user.id', $article->user_id) }}">{{ $article->profile->name }}</a></li>
                                        <li><i class="icon-eye"></i> {{ $article->looks->count() }}</li>
                                        <li class="stat-like">
                                          @include('statistics.like-sm', array('type' => $article, 'type_name' => 'article'))
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        @endforeach
                    {{ $articles->links() }}
                    @else
                        Нет статей.
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop

app/views/articles/create.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Статья создать | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')
{{ HTML::script('themes/site/js/jquery.ui.widget.js') }}
{{ HTML::script('themes/site/js/jquery.fileupload.js') }}
{{ HTML::script('themes/site/js/bootstrap-filestyle.js') }}
{{ HTML::script('/tinymce/tinymce.min.js') }}
{{ HTML::script('/tinymce/tinymce_editor.js') }}
<script type="text/javascript">
    editor_config.selector = ".body";
    tinymce.init(editor_config);
    $(document).ready(function() {
        //$.fn.uploadImage('articles');
        admin.article('articles');
    });
</script>
@stop

@section('content')
                
<div id="pages">
<div style="margin:20px;" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Создать статью</h1>
  </div>
{{ Form::open(array('route' => 'admin.articles.store', 'role' => 'form', 'id' => 'form-create-articles')) }}
  <div class="panel-body">
    {{ Form::hidden('user_id', Sentry::getUser()->id) }}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">Основное</a></li>
      <li><a href="#meta" data-toggle="tab">Мета</a></li>
    </ul>
    
    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="home">
            
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                {{ Form::label('name', 'Заголовок') }}
                {{ Form::text('name', null, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
                {{ Form::label('body', 'Содержание') }}
                {{ Form::textarea('body', null, array('class' => 'form-control body', 'rows' => 10)) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('image_ajax', 'Картинка') }}
                <div class="image-upload"></div>
                <input id="input-image" type="file">
            </div>
                
                
            <div class="form-group">
                {{ Form::label('slug', 'Путь') }}
                {{ Form::text('slug', null, array('class' => 'form-control')) }}
            </div>
                
            <div class="checkbox">
                <label class="i-checks m-b-md">
                    {{ Form::hidden('status', 0) }}
                    {{ Form::checkbox('status', 1, true) }} <i></i> Опубликовано
                </label>
            </div>
            
      </div>
      <div class="tab-pane" id="meta">
            
            <div class="form-group">
                {{ Form::label('title', 'Заголовок') }}
                {{ Form::text('title', null, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('keywords', 'Ключенвые слова') }}
                {{ Form::text('keywords', null, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('description', 'Описание') }}
                {{ Form::textarea('description', null, array('class' => 'form-control', 'rows' => 5)) }}
            </div>
                
      </div>
    </div>

  </div><!--panel-body-->
  <div class="panel-footer">
    {{ HTML::decode(Form::button('<i class="fa fa-floppy-o"></i> Сохранить', array('class' => 'btn btn-dark', 'type' => 'submit'))) }}
  </div>
{{ Form::close() }}
</div>
</div>
@stop

app/views/articles/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="deleteArticles-{{ $article->id }}" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Удалить страницу?</h4>
      </div>
       {{ Form::open(array('route' => array('admin.articles.destroy', $article->id), 'method' => 'delete', 'role' => 'form')) }} 
            <div class="modal-body text-center">
              <i class="fa fa-warning text-danger" style="font-size: 72px;"></i><br>
              <p>Внимание! Вы пытаетесь удалить страницу.<br> После удаления восстановыть будет нельзя.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              {{ HTML::decode(Form::button('<i class="fa fa-trash-o"></i> Удалить', array('class' => 'btn btn-danger', 'type' => 'submit'))) }}
            </div>
        {{ Form::close() }}
    </div>
  </div>
</div>

app/views/articles/edit.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Статьи редактировать | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')
{{ HTML::script('themes/site/js/jquery.ui.widget.js') }}
{{ HTML::script('themes/site/js/jquery.fileupload.js') }}
{{ HTML::script('themes/site/js/bootstrap-filestyle.js') }}
{{ HTML::script('/tinymce/tinymce.min.js') }}
{{ HTML::script('/tinymce/tinymce_editor.js') }}
<script type="text/javascript">
    editor_config.selector = ".body";
    tinymce.init(editor_config);
     $(document).ready(function() {
        admin.article('articles');
    });
</script>
@stop

@section('content')
                
<div id="pages">
<div style="margin:20px;" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Редактировать статью</h1>
  </div>
{{ Form::open(array('route' => array('admin.articles.update', $article->id), 'method' => 'put', 'role' => 'form', 'id' => 'form-edit-articles')) }}
  <div class="panel-body">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">Основное</a></li>
      <li><a href="#meta" data-toggle="tab">Мета</a></li>
    </ul>
    
    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="home">
            
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                {{ Form::label('name', 'Заголовок') }}
                {{ Form::text('name', $article->name, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
                {{ Form::label('body', 'Содержание') }}
                {{ Form::textarea('body', $article->body, array('class' => 'form-control body', 'rows' => 10)) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('image_ajax', 'Картинка') }}
                <div class="image-upload">@include('site.upload-image', ['folder' => 'articles', 'filename' => $article->image])</div>
                <input id="input-image" type="file">
            </div>
                
            <div class="form-group">
                {{ Form::label('slug', 'Путь') }}
                {{ Form::text('slug', $article->slug, array('class' => 'form-control')) }}
            </div>
                
            <div class="checkbox">
                <label class="i-checks m-b-md">
                    {{ Form::hidden('status', 0) }}
                    {{ Form::checkbox('status', 1, $article->status) }} <i></i> Опубликовано
                </label>
            </div>
            
      </div>
      <div class="tab-pane" id="meta">
            
            <div class="form-group">
                {{ Form::label('title', 'Заголовок') }}
                {{ Form::text('title', $article->title, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('keywords', 'Ключенвые слова') }}
                {{ Form::text('keywords', $article->keywords, array('class' => 'form-control')) }}
            </div>
                
            <div class="form-group">
                {{ Form::label('description', 'Описание') }}
                {{ Form::textarea('description', $article->description, array('class' => 'form-control', 'rows' => 5)) }}
            </div>
                
      </div>
    </div>

  </div><!--panel-body-->
  <div class="panel-footer">
    {{ HTML::decode(Form::button('<i class="fa fa-floppy-o"></i> Сохранить', array('class' => 'btn btn-dark', 'type' => 'submit'))) }}
  </div>
{{ Form::close() }}
</div>
</div>
@stop

app/views/articles/index.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Статьи | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')

@stop

@section('content')
                
<div id="pages">

<div style="margin:20px;" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Статьи</h1>
  </div>
  <div class="panel-body">
    <a style="margin:0 20px 20px 0" href="{{ route('admin.articles.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Создать</a>
    @if($articles->count())
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Заголовок</th>
                    <th>Путь</th>
                    <th>Дата</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach($articles as $article)
                <tr>
                    <td>{{ $article->id }}</td>
                    <td><a href="{{ route('articles.show', $article->slug) }}">{{ $article->name }}</a></td>
                    <td>{{ $article->slug }}</td>
                    <td width="160">{{ $article->created_at }}</td>
                    <td>{{ ($article->status == 1) ? 'опубликовано' : 'не опубликовано' }}</td>
                    <td width="100">
                        <a href="{{ route('admin.articles.edit', $article->id) }}" title="Редактировать" class="btn btn-sm btn-icon btn-info"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:" data-toggle="modal" data-target="#deleteArticles-{{ $article->id }}" title="Удалить" class="btn btn-sm btn-icon btn-danger"><i class="fa fa-trash-o"></i></a>
                        @include('articles.delete', $article)
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $articles->links() }}
    @else
        <div style="margin:20px;">Нет страниц.</div>
    @endif
  </div>
</div>

</div>
@stop

app/views/articles/show.blade.php
@extends('site')

@section('description')
   <meta name="description" content="{{ $article->description or '' }}">
@stop

@section('keywords')
    <meta name="keywords" content="{{ $article->keywords or '' }}">
@stop

@section('title')
    <title>{{ ($article->title) ? $article->title : $article->name }} | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')

@stop

@section('content')
                
<div id="page">
    <div class="panel-body">
        <div class="bg-light lter b-b wrapper-md ng-scope">
            <h1 class="m-n font-thin h3">Статьи</h1>
             @if(Sentry::check())   
                @if(Sentry::getUser()->hasAccess('dashboard.doc'))
                    <a href="{{ route('admin.articles.edit', $article->id) }}" title="Редактировать" class="btn btn-sm btn-icon btn-info pull-right" style="margin-top:-25px;"><i class="fa fa-pencil"></i></a>
                @endif
             @endif
        </div>
        <div class="blog-post">
            <div class="panel">
                <div class="wrapper-lg">
                    <h2 class="m-t-none">{{ $article->name }}</h2>
                    <div>
                        @if($article->image)
                            <img src="{{ route('image.folder', array('articles', $article->image, 350, 350, 'center')) }}" class="img-thumbnail m-r-md pull-left">
                        @endif
                      {{ $article->body }}
                    </div>
                    <div class="line line-lg b-b b-light"></div>
                    <ul class="stats list-inline text-muted">
                        <li><i class="icon-calendar"></i> {{ date('d.m.Y', strtotime($article->created_at)) }}</li>
                        <li><i class="icon-user"></i> <a class="text-muted" href="{{ route('user.id', $article->user_id) }}">{{ $article->profile->name }}</a></li>
                        <li><i class="icon-eye"></i> {{ $article->looks->count() }}</li>
                        <li class="stat-like">
                          @include('statistics.like-sm', array('type' => $article, 'type_name' => 'article'))
                        </li>
                    </ul>
                </div>
                
            </div>
        </div>
    </div>
</div>
@stop