app/routes.php
<?php
use Faker\Factory as Faker;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Online::updateCurrent();

Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Admin Routes
Route::group(['before' => 'auth|admin'], function()
{
        Route::group(array('prefix' => 'admin'), function()
        {
            //Route::get('users', array('as' => 'admin.users', 'uses' => 'UsersController@users'));
	    //Route::get('roles', array('as' => 'admin.roles', 'uses' => 'UsersController@roles'));
	    Route::resource('pages', 'PagesController');
	    Route::resource('uslugis', 'UslugisController');
	    Route::resource('articles', 'ArticlesController');
	    Route::resource('histories', 'HistoriesController');
	    Route::resource('albums', 'AlbumsController');
	    Route::resource('photos', 'PhotosController');
	    Route::resource('comments', 'CommentsController');
	    Route::resource('users', 'UsersController');
	    Route::resource('menu', 'MenunamesController');
	    Route::post('/set/admin', array('as' => 'admin.set.admin', 'uses' => 'UsersController@set_admin'));
        });
});

# Registration
Route::group(['before' => 'guest'], function()
{
     Route::post('/user/login', array('as' => 'user.login', 'uses' => 'UsersController@login'));
     Route::get('/user/register', array('as' => 'user.register', 'uses' => 'UsersController@register'));
     Route::post('/user/register', array('as' => 'user.register.post', 'uses' => 'UsersController@register_post'));
     Route::get('/user/activate/{activationCode}', array('as' => 'user.activate', 'uses' => 'UsersController@activate'));
     
	
});

# Авторизованый
Route::group(['before' => 'auth'], function()
{
	Route::get('/user/logout', array('as' => 'user.logout', 'uses' => 'UsersController@user_logout'));
	
	Route::get('/user/id-{id}', array('as' => 'user.id', 'uses' => 'UsersController@information'));
	Route::get('/user/id-{id}/settings', array('as' => 'user.settings', 'uses' => 'UsersController@settings'));
	Route::post('/user/id-{id}/settings', array('as' => 'user.settings.save', 'uses' => 'UsersController@settings_save'));
	Route::get('/user/id-{id}/information', array('as' => 'user.information', 'uses' => 'UsersController@information'));
	Route::post('/user/id-{id}/information/about/save', array('as' => 'user.information.about.save', 'uses' => 'UsersController@information_about_save'));
	Route::post('/user/id-{id}/information/thinking/save', array('as' => 'user.information.thinking.save', 'uses' => 'UsersController@information_thinking_save'));
	Route::post('/user/profile/save/name', array('as' => 'user.profile.save.name', 'uses' => 'UsersController@user_profile_save_name'));
	Route::post('/user/profile/save/telephone', array('as' => 'user.profile.save.telephone', 'uses' => 'UsersController@user_profile_save_telephone'));
	Route::post('/user/profile/save/city', array('as' => 'user.profile.save.city', 'uses' => 'UsersController@user_profile_save_city'));
	Route::post('/user/profile/save/bithday', array('as' => 'user.profile.save.bithday', 'uses' => 'UsersController@user_profile_save_bithday'));
	Route::post('/user/profile/save/gender', array('as' => 'user.profile.save.gender', 'uses' => 'UsersController@user_profile_save_gender'));
	Route::post('/user/profile/save/gender-search', array('as' => 'user.profile.save.gender.search', 'uses' => 'UsersController@user_profile_save_gender_search'));
	Route::post('/user/profile/save/point', array('as' => 'user.profile.save.point', 'uses' => 'UsersController@user_profile_save_point'));
	Route::post('/user/profile/save/work', array('as' => 'user.profile.save.work', 'uses' => 'UsersController@user_profile_save_work'));
	Route::post('/user/profile/save/vuz', array('as' => 'user.profile.save.vuz', 'uses' => 'UsersController@user_profile_save_vuz'));
	Route::post('/user/profile/save/school', array('as' => 'user.profile.save.school', 'uses' => 'UsersController@user_profile_save_school'));
	
	Route::get('/user/id-{id}/friends', array('as' => 'user.friends', 'uses' => 'UsersController@friends'));
	Route::get('/friends/add/{id}', array('as' => 'friends.add', 'uses' => 'UsersController@friendsAdd'));
	Route::get('/friends/apply/{id}', array('as' => 'friends.apply', 'uses' => 'UsersController@applyFriend'));
	Route::get('/friends/cencel/{id}', array('as' => 'friends.cencel', 'uses' => 'UsersController@cencelFriend'));
	Route::get('/friends/del/{id}', array('as' => 'friends.del', 'uses' => 'UsersController@delFriend'));
	
	Route::post('/upload/avatar/{id}', array('as' => 'upload.avatar', 'uses' => 'FileController@uploadAvatar'));
	Route::post('/upload/fon/{id}', array('as' => 'upload.fon', 'uses' => 'FileController@uploadFon'));
	Route::controller('filemanager', 'FilemanagerLaravelController');
	Route::post('/upload/{folder}', array('as' => 'upload.image', 'uses' => 'FileController@uploadImage'));
	Route::post('/upl/photos', array('as' => 'upload.photos', 'uses' => 'FileController@uploadPhotos'));
	
	Route::get('/profiles/all', array('as' => 'profiles', 'uses' => 'UsersController@profiles'));
	
	Route::get('/user/id-{id}/photos', array('as' => 'user.photos', 'uses' => 'AlbumsController@photos'));
	Route::get('/user/id-{id}/photos/album/{slug}', array('as' => 'user.album', 'uses' => 'PhotosController@album'));
	Route::resource('albums', 'AlbumsController');
	Route::resource('photos', 'PhotosController');
	Route::get('photos/{id}/nextprev', array('as' => 'photos.nextprev', 'uses' => 'PhotosController@nextprev'));
        
	Route::resource('comments', 'CommentsController');
	
	Route::get('/user/id-{id}/messages', array('as' => 'user.messages', 'uses' => 'ChatsController@messages'));
	Route::resource('histories', 'HistoriesController', array('only' => array('create', 'store')));
	Route::post('/chats/sendme/ajax', array('as' => 'chats.sendme.ajax', 'uses' => 'ChatsController@sendME'));
	
	Route::post('/pay/success', array('as' => 'pay.success', 'uses' => 'HomeController@success'));
	Route::post('/pay/fail', array('as' => 'pay.fail', 'uses' => 'HomeController@fail'));
	Route::post('/pay/pending', array('as' => 'pay.pending', 'uses' => 'HomeController@pending'));
	
	Route::post('/star/add', array('as' => 'star.add', 'uses' => 'StarsController@store'));
	
});

Route::get('/', array('as' => 'front', 'uses' => 'HomeController@showWelcome'));
Route::get('/image/users/{id}/{w}/{h}', array('as' => 'user.avatar', 'uses' => 'FileController@avatar'));
Route::get('/image/users/load/{name}/{w}/{h}', array('as' => 'user.avatar.load', 'uses' => 'FileController@avatar_load'));
Route::any('/{slug}', array('as' => 'pages.view', 'uses' => 'PagesController@view'));
Route::get('/image/filemanager/{name}/{w}/{h}/{position}', array('as' => 'image.filemanager', 'uses' => 'FileController@filemanager'));
Route::get('/image/{folder}/{name}/{w}/{h}/{position}', array('as' => 'image.folder', 'uses' => 'FileController@imageFolder'));

Route::get('/uslugi/{slug}', array('as' => 'uslugis.view', 'uses' => 'UslugisController@view'));
Route::get('/article/{slug}', array('as' => 'articles.show', 'uses' => 'ArticlesController@show'));
Route::get('/articles/all', array('as' => 'articles', 'uses' => 'ArticlesController@articles'));
Route::get('/history/{slug}', array('as' => 'histories.show', 'uses' => 'HistoriesController@show'));
Route::get('/histories/all', array('as' => 'histories', 'uses' => 'HistoriesController@histories'));

Route::get('/profiles/json', array('as' => 'profiles.json', 'uses' => 'UsersController@profilesJson'));

Route::get('/profiles/load/chat', array('as' => 'profiles.load.chat', 'uses' => 'ChatsController@loadChat'));
Route::post('/chats/send/message/ajax', array('as' => 'chats.send.message.ajax', 'uses' => 'ChatsController@sendMessageAjax'));
Route::post('/chats/load/{id}/ajax', array('as' => 'chats.load.message.ajax', 'uses' => 'ChatsController@loadMessageAjax'));
Route::post('/set/like', array('as' => 'set.like', 'uses' => 'StatisticsController@setLike'));

require app_path().'/menu.php';

app/models/User.php
<?php

//use Illuminate\Auth\UserTrait;
//use Illuminate\Auth\UserInterface;
//use Illuminate\Auth\Reminders\RemindableTrait;
//use Illuminate\Auth\Reminders\RemindableInterface;
//use Cartalyst\Sentry\Users\Eloquent\User as SentryUserModel;
use Cartalyst\Sentry\Users\Eloquent\User as SentryModel;
use Jenssegers\Date\Date;
//class User extends SentryUserModel implements UserInterface, RemindableInterface {
class User extends SentryModel {

	//use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	//protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');
	
	public static $rules = array(
		'email' => 'required|email',
		'password' => 'required|min:6|confirmed',
		'password_confirmation' => 'required|min:6',
		'name' => 'required',
		'gender' => 'required',
		'gender_search' => 'required',
		'adres' => 'required',
		'telephone' => 'required',
		//'pravila' => 'required',
	);
	
	public static $messages = array(
               
	       'email.required'                 => 'Поле "Почта" обязательно для заполнения',
	       'password.required'              => 'Поле "Пароль" обязательно для заполнения',
	       'password_confirmation.required' => 'Поле "Повтор пароля" обязательно для заполнения',
	       'password.confirmed'             => 'Поле "Повтор пароля" несовпадает',
	       'name.required'                  => 'Поле "Имя" обязательно для заполнения',
	       
        );
	
	public function profile()
	{
	    return $this->hasOne('Profile','user_id');
	}
	
	   
	public function albums()
	{
	    return $this->hasMany('Album','user_id');
	}
	
	public function photos()
	{
	    return $this->hasMany('Photo');
	}
	
	public function friendsReq()
	{
	    return $this->hasMany('FriendReq', 'user_to');
	}
	
	public function isOnline($id)
	{
	    
	    $online = Online::where('user_id', $id)->first();
	    
	    if($online)
	    {
		return true;
	    }
	    else
	    {
		return false;
	    }
	   
	}
	
	/* public function status
	 * @param $id
	 *-----------------------------------
	 *|
	 *-----------------------------------
	 */
	
	public function status($id) {
	    
	    if($id == 1)
	    {
		return 'активный';
	    }
	    else
	    {
		return 'заблокирован';
	    }
	    
	    
	}
	
	
	
	
	

}

app/views/admin/users/create.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Создать пользователя | {{ Config::get('site.site_name') }}</title>
@stop

@section('google')
    {{ HTML::script('https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places') }}
@stop

@section('script')
    {{ HTML::script('themes/site/js/infobox.js') }}
    {{ HTML::script('themes/site/js/site.js') }}
@stop

@section('content')
                
<div id="pages">

<div style="margin:20px;" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Создать пользователя</h1>
  </div>
  <div class="panel-body">
    {{ Form::open(array('route' => 'admin.users.store', 'role' => 'form', 'class' => 'form')) }}
        
        <div class="form-group">
            <label for="name">Имя</label>
            {{ Form::text('name', null, array('class' => 'form-control')) }}
        </div>
            
        <div class="form-group">
            <label for="email">Почта</label>
            {{ Form::email('email', null, array('class' => 'form-control')) }}
        </div>
            
        <div class="form-group">
            <label for="password">Пароль</label>
            {{ Form::password('password', array('class' => 'form-control')) }}
        </div>
            
            
        <div class="form-group">
            <label for="adres">Живет</label>
            {{ Form::text('adres', null, array('class' => 'form-control', 'id' => 'geocomplete')) }}
        </div>
            
        <div class="form-group">
            <label for="telephone">Телефон</label>
            {{ Form::text('telephone', null, array('class' => 'form-control')) }}
        </div>
            
        <div class="form-group pull-in clearfix">
            <div class="col-sm-6">
              <label>Пол</label>&emsp;
              <div id="gender-group" class="btn-group" data-toggle="buttons">
               <label class="btn btn-default">
                 {{ Form::radio('gender', 1) }}<i class="icon-symbol-male"></i> Мужчина
               </label>
               <label class="btn btn-default">
                 {{ Form::radio('gender', 2) }}<i class="icon-symbol-female "></i> Женщина
               </label>
             </div>
            </div>
            <div class="col-sm-6">
              <label>Ищет пол</label>&emsp;
              <div id="gender-search-group" class="btn-group" data-toggle="buttons">
               <label class="btn btn-default">
                 {{ Form::radio('gender_search', 1) }}<i class="icon-symbol-male"></i> Мужчину
               </label>
               <label class="btn btn-default">
                 {{ Form::radio('gender_search', 2) }}<i class="icon-symbol-female "></i> Женщину
               </label>
             </div>
            </div>
        </div>
        {{ Form::hidden('city', null) }}   
        {{ Form::hidden('lat', null) }}
        {{ Form::hidden('lng', null) }}
        
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    {{ Form::close() }}
    
  </div>
</div>

</div>
@stop

app/views/admin/users/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="deleteUser-{{ $user->id }}" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Удалить пользователя?</h4>
      </div>
       {{ Form::open(array('route' => array('admin.users.destroy', $user->id), 'method' => 'delete', 'role' => 'form')) }} 
            <div class="modal-body text-center">
              <i class="fa fa-warning text-danger" style="font-size: 72px;"></i><br>
              <p>Внимание! Вы пытаетесь удалить пользователя.<br> После удаления восстановыть будет нельзя.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              {{ HTML::decode(Form::button('<i class="fa fa-trash-o"></i> Удалить', array('class' => 'btn btn-danger', 'type' => 'submit'))) }}
            </div>
        {{ Form::close() }}
    </div>
  </div>
</div>

app/views/admin/users/index.blade.php
@extends('site')

@section('description')
   <meta name="description" content="">
@stop

@section('keywords')
    <meta name="keywords" content="">
@stop

@section('title')
    <title>Пользователи | {{ Config::get('site.site_name') }}</title>
@stop

@section('script')

@stop

@section('content')
                
<div id="pages">

<div style="margin:20px;" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Пользователи</h1>
  </div>
  <div class="panel-body">
    <a href="{{ route('admin.users.create') }}" class="btn btn-success m-b-20"><i class="fa fa-plus"></i> Создать</a>
    
    @if($admins->count())
        <h2>Администраторы</h2>
            
        {{ Form::open(array('route' => 'admin.set.admin', 'role' => 'form', 'class' => 'form m-b-20')) }}
            <div class="form-group">
                <label for="email">Сделать пользователя админом</label>
                {{ Form::email('email', null, array('class' => 'form-control', 'placeholder' => 'Почта пользователя')) }}
            </div>
            {{ Form::submit('Применить', array('class' => 'btn btn-primary')) }}
        {{ Form::close() }}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Почта / Логин</th>
                    <th>Дата</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach($admins as $admin)
                <tr>
                    <td>{{ $admin->id }}</td>
                    <td><a href="javascript:">{{ $admin->email }}</a></td>
                    <td>{{ $admin->created_at }}</td>
                    <td>{{ $admin->status($admin->activated) }}</td>
                    <td>
                        <a href="{{ route('user.settings', $admin->id) }}" title="Редактировать" class="btn btn-sm btn-icon btn-info"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif
    
    
    
    @if($users->count())
        <h2>Пользователи</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Почта / Логин</th>
                    <th>Дата</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td><a href="javascript:">{{ $user->email }}</a></td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->status($user->activated) }}</td>
                    <td>
                        <a href="{{ route('user.settings', $user->id) }}" title="Редактировать" class="btn btn-sm btn-icon btn-info"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:" data-toggle="modal" data-target="#deleteUser-{{ $user->id }}" title="Удалить" class="btn btn-sm btn-icon btn-danger"><i class="fa fa-trash-o"></i></a>
                       @include('admin.users.delete', $user)
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $users->links() }}
    @else
        <div style="margin:20px;">Нет пользователей.</div>
    @endif
  </div>
</div>

</div>
@stop